@startuml

/'"单独售（租）部件功能（快捷出单）：存量在用商户单独要买部件
走装机工单流程；
根据“机身号/终端号”使用状态判断是新装机还是部件销售；
  已经使用：只产生部件的出库流水,并且收据单体现出部件信息
  未使用：产生终端、部件的出库流水
  问题：如果系统无“机身号/终端号”有问题"
'/

start
:装机工单;
:新装机;
if (机身号/终端号是否使用?) then (no)
    :正常装机流程;
    :装机输入关联部件，生成部件组合表;
    :不支持绑定IC卡;
    if (审核是否拒绝?) then (no)
    :审核之后终端表生成，部件组合关联终端;
    :部件关联自动跳过;
    else (yes)
    :部件状态退回到未装机状态;
    :修改支持一个终端提交，工单模式不可更改;
    endif
else (yes)
    :工单模式：单独售租;
    :根据终端号带出已关联部件信息，可添加其他部件;
    :商户号是填写还是隐藏还是带出？
    :部件关联自动跳过;
    :派发：产生部件的出库流水;
    :收据单体现出部件信息?根据工单能查询到部件信息;
endif

stop
@enduml