@startuml

/'"1. 增加一个功能“快签出机”
  2. 页面元素与“装机单”相似，但是只能输入终端号并且带出机身信息（查询主机库存表）
  3. 提交之后判断：
  a. 该终端的主机库存信息=“已入库”状态
  b. 终端表中是否存在此终端号并商户号为空
  c. 部件表中检查机身=未使用
  d. 商户的代理商与主机库存的代理商一致
  满足以上条件认为是DM系统快签的主机，允许装机
    审核时不用新增数据（主机库存，终端信息表，密钥表），只需要补全商户的信息即可（更新 主机库存，终端信息表）。
    后面的流程与装机流程一样
  "

'/

start
:快签出机工单(页面元素与“装机单”相似);
:输入终端号并且带出机身信息(查询主机库存表);
if (主机库存终端是否已入库?) then (yes)
    if (终端表是否存在?) then (yes)
        if (商户号是否为空?) then (yes)
        else (no)
        :提示：终端表商户号
        不为空，不能快签出机;
        endif
    else (no)
    :提示：终端表不存在
    此终端号，不能快签出机;
    endif
    if (部件表机身是否未使用?) then (yes)
    else (no)
    :提示：部件不是未使用，
    不能快签出机;
    endif
    if (商户的代理商与主机库存的代理商是否一致?) then (yes)
    else (no)
    :提示：代理商不一致，
    不能快签出机;
    endif
else (no)
    :提示：不是已入库终端
    不能快签出机;
endif
:工单模式：快签出机;
:审核：更新主机库存，终端信息表商户的信息;
stop
@enduml