@startuml

/'"做法：
  修改租赁转销售流程
  1. 只要出机方式为租赁都能查询到
  2. 完成状态的单：走以前的逻辑
  3. 未完成状态的单：
  a) 原费用单，收据单作废；
  b) 流水[增加一笔租赁入库流水、增加一笔销售出库流水]，产生新的销售收据单
  注：新的工单记录上一笔工单号
  "
'/

start
:租赁转销售工单;
if (装机租赁工单是否完成?) then (yes)
    :正常工单流程;
    if (装机租赁工单是否完成?) then (yes)
    :正常工单流程;
stop
else(no)
    :审核：原收据单作废;
    :审核：增加一笔租赁入库流水、一笔销售出库流水;
    :RelateId为上一笔工单号;
    :租赁转销售工单不支持撤机换机;
stop
@enduml